/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Test.Thrift
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class BiggerObjectWithBytesThrift : TBase
  {
    private string _Uri;
    private string _Header;
    private byte[] _Content;

    public string Uri
    {
      get
      {
        return _Uri;
      }
      set
      {
        __isset.Uri = true;
        this._Uri = value;
      }
    }

    public string Header
    {
      get
      {
        return _Header;
      }
      set
      {
        __isset.Header = true;
        this._Header = value;
      }
    }

    public byte[] Content
    {
      get
      {
        return _Content;
      }
      set
      {
        __isset.Content = true;
        this._Content = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool Uri;
      public bool Header;
      public bool Content;
    }

    public BiggerObjectWithBytesThrift() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 10:
              if (field.Type == TType.String) {
                Uri = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 20:
              if (field.Type == TType.String) {
                Header = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 30:
              if (field.Type == TType.String) {
                Content = iprot.ReadBinary();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("BiggerObjectWithBytesThrift");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Uri != null && __isset.Uri) {
          field.Name = "Uri";
          field.Type = TType.String;
          field.ID = 10;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Uri);
          oprot.WriteFieldEnd();
        }
        if (Header != null && __isset.Header) {
          field.Name = "Header";
          field.Type = TType.String;
          field.ID = 20;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Header);
          oprot.WriteFieldEnd();
        }
        if (Content != null && __isset.Content) {
          field.Name = "Content";
          field.Type = TType.String;
          field.ID = 30;
          oprot.WriteFieldBegin(field);
          oprot.WriteBinary(Content);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("BiggerObjectWithBytesThrift(");
      bool __first = true;
      if (Uri != null && __isset.Uri) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Uri: ");
        __sb.Append(Uri);
      }
      if (Header != null && __isset.Header) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Header: ");
        __sb.Append(Header);
      }
      if (Content != null && __isset.Content) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Content: ");
        __sb.Append(Content);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
