// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BiggerObjectWithBytesProtobuf.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from BiggerObjectWithBytesProtobuf.proto</summary>
public static partial class BiggerObjectWithBytesProtobufReflection {

  #region Descriptor
  /// <summary>File descriptor for BiggerObjectWithBytesProtobuf.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static BiggerObjectWithBytesProtobufReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CiNCaWdnZXJPYmplY3RXaXRoQnl0ZXNQcm90b2J1Zi5wcm90byJNCh1CaWdn",
          "ZXJPYmplY3RXaXRoQnl0ZXNQcm90b2J1ZhILCgNVcmkYCiABKAkSDgoGSGVh",
          "ZGVyGBQgASgJEg8KB0NvbnRlbnQYHiABKAxiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::BiggerObjectWithBytesProtobuf), global::BiggerObjectWithBytesProtobuf.Parser, new[]{ "Uri", "Header", "Content" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class BiggerObjectWithBytesProtobuf : pb::IMessage<BiggerObjectWithBytesProtobuf> {
  private static readonly pb::MessageParser<BiggerObjectWithBytesProtobuf> _parser = new pb::MessageParser<BiggerObjectWithBytesProtobuf>(() => new BiggerObjectWithBytesProtobuf());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<BiggerObjectWithBytesProtobuf> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::BiggerObjectWithBytesProtobufReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public BiggerObjectWithBytesProtobuf() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public BiggerObjectWithBytesProtobuf(BiggerObjectWithBytesProtobuf other) : this() {
    uri_ = other.uri_;
    header_ = other.header_;
    content_ = other.content_;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public BiggerObjectWithBytesProtobuf Clone() {
    return new BiggerObjectWithBytesProtobuf(this);
  }

  /// <summary>Field number for the "Uri" field.</summary>
  public const int UriFieldNumber = 10;
  private string uri_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Uri {
    get { return uri_; }
    set {
      uri_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "Header" field.</summary>
  public const int HeaderFieldNumber = 20;
  private string header_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Header {
    get { return header_; }
    set {
      header_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "Content" field.</summary>
  public const int ContentFieldNumber = 30;
  private pb::ByteString content_ = pb::ByteString.Empty;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pb::ByteString Content {
    get { return content_; }
    set {
      content_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as BiggerObjectWithBytesProtobuf);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(BiggerObjectWithBytesProtobuf other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Uri != other.Uri) return false;
    if (Header != other.Header) return false;
    if (Content != other.Content) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Uri.Length != 0) hash ^= Uri.GetHashCode();
    if (Header.Length != 0) hash ^= Header.GetHashCode();
    if (Content.Length != 0) hash ^= Content.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Uri.Length != 0) {
      output.WriteRawTag(82);
      output.WriteString(Uri);
    }
    if (Header.Length != 0) {
      output.WriteRawTag(162, 1);
      output.WriteString(Header);
    }
    if (Content.Length != 0) {
      output.WriteRawTag(242, 1);
      output.WriteBytes(Content);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Uri.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Uri);
    }
    if (Header.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(Header);
    }
    if (Content.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeBytesSize(Content);
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(BiggerObjectWithBytesProtobuf other) {
    if (other == null) {
      return;
    }
    if (other.Uri.Length != 0) {
      Uri = other.Uri;
    }
    if (other.Header.Length != 0) {
      Header = other.Header;
    }
    if (other.Content.Length != 0) {
      Content = other.Content;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 82: {
          Uri = input.ReadString();
          break;
        }
        case 162: {
          Header = input.ReadString();
          break;
        }
        case 242: {
          Content = input.ReadBytes();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
