// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SmallObjectWithStringsProtobuf.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from SmallObjectWithStringsProtobuf.proto</summary>
public static partial class SmallObjectWithStringsProtobufReflection {

  #region Descriptor
  /// <summary>File descriptor for SmallObjectWithStringsProtobuf.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static SmallObjectWithStringsProtobufReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CiRTbWFsbE9iamVjdFdpdGhTdHJpbmdzUHJvdG9idWYucHJvdG8iZAoeU21h",
          "bGxPYmplY3RXaXRoU3RyaW5nc1Byb3RvYnVmEg8KB1N0cmluZzEYCiABKAkS",
          "DwoHU3RyaW5nMhgUIAEoCRIPCgdTdHJpbmczGB4gASgJEg8KB1N0cmluZzQY",
          "KCABKAliBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::SmallObjectWithStringsProtobuf), global::SmallObjectWithStringsProtobuf.Parser, new[]{ "String1", "String2", "String3", "String4" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class SmallObjectWithStringsProtobuf : pb::IMessage<SmallObjectWithStringsProtobuf> {
  private static readonly pb::MessageParser<SmallObjectWithStringsProtobuf> _parser = new pb::MessageParser<SmallObjectWithStringsProtobuf>(() => new SmallObjectWithStringsProtobuf());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<SmallObjectWithStringsProtobuf> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SmallObjectWithStringsProtobufReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SmallObjectWithStringsProtobuf() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SmallObjectWithStringsProtobuf(SmallObjectWithStringsProtobuf other) : this() {
    string1_ = other.string1_;
    string2_ = other.string2_;
    string3_ = other.string3_;
    string4_ = other.string4_;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public SmallObjectWithStringsProtobuf Clone() {
    return new SmallObjectWithStringsProtobuf(this);
  }

  /// <summary>Field number for the "String1" field.</summary>
  public const int String1FieldNumber = 10;
  private string string1_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string String1 {
    get { return string1_; }
    set {
      string1_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "String2" field.</summary>
  public const int String2FieldNumber = 20;
  private string string2_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string String2 {
    get { return string2_; }
    set {
      string2_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "String3" field.</summary>
  public const int String3FieldNumber = 30;
  private string string3_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string String3 {
    get { return string3_; }
    set {
      string3_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "String4" field.</summary>
  public const int String4FieldNumber = 40;
  private string string4_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string String4 {
    get { return string4_; }
    set {
      string4_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as SmallObjectWithStringsProtobuf);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(SmallObjectWithStringsProtobuf other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (String1 != other.String1) return false;
    if (String2 != other.String2) return false;
    if (String3 != other.String3) return false;
    if (String4 != other.String4) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (String1.Length != 0) hash ^= String1.GetHashCode();
    if (String2.Length != 0) hash ^= String2.GetHashCode();
    if (String3.Length != 0) hash ^= String3.GetHashCode();
    if (String4.Length != 0) hash ^= String4.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (String1.Length != 0) {
      output.WriteRawTag(82);
      output.WriteString(String1);
    }
    if (String2.Length != 0) {
      output.WriteRawTag(162, 1);
      output.WriteString(String2);
    }
    if (String3.Length != 0) {
      output.WriteRawTag(242, 1);
      output.WriteString(String3);
    }
    if (String4.Length != 0) {
      output.WriteRawTag(194, 2);
      output.WriteString(String4);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (String1.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(String1);
    }
    if (String2.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(String2);
    }
    if (String3.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(String3);
    }
    if (String4.Length != 0) {
      size += 2 + pb::CodedOutputStream.ComputeStringSize(String4);
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(SmallObjectWithStringsProtobuf other) {
    if (other == null) {
      return;
    }
    if (other.String1.Length != 0) {
      String1 = other.String1;
    }
    if (other.String2.Length != 0) {
      String2 = other.String2;
    }
    if (other.String3.Length != 0) {
      String3 = other.String3;
    }
    if (other.String4.Length != 0) {
      String4 = other.String4;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 82: {
          String1 = input.ReadString();
          break;
        }
        case 162: {
          String2 = input.ReadString();
          break;
        }
        case 242: {
          String3 = input.ReadString();
          break;
        }
        case 322: {
          String4 = input.ReadString();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
